version: "3"
services:
  explorer-api:
    build: .
    image: tinyyxx/explorer-api01:latest
    depends_on:
      - rsk-node
      - mongod
    container_name: explorer-api01
    ports:
      - "3003:3003"
  rsk-node:
    build: ./dockerized/rsk-node
    image: tinyyxx/rsk-node01:latest
    container_name: rsk-node01
    ports:
      - "4444:4444"
      - "5050:5050"
      - "50505:50505"
  mongod:
    build: ./dockerized/mongod
    image: tinyyxx/mongod01:latest
    container_name: mongod01
    ports:
      - "27017:27017"
